#!/bin/sh

# Check if XDG_RUNTIME_DIR exists, if not, create it
if [ ! -d "$XDG_RUNTIME_DIR" ]; then
    mkdir -p "$XDG_RUNTIME_DIR"
    chown -R appuser:appgroup "$XDG_RUNTIME_DIR"  # Ensure permissions are correct
fi

# Start Xpra with HTTP upgrades enabled
xpra start $XPRA_DISPLAY \
    --pulseaudio=no \
    --start-child="$@" \
    --bind-tcp=0.0.0.0:$XPRA_PORT \
    --http=0.0.0.0:$HTTP_PORT \  # Enable HTTP upgrades
    --no-daemon \
    --exit-with-children
